# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psc < Formula
  desc "TUI-based daemon for running large-scale PostgreSQL data fix migrations"
  homepage ""
  version "2.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.0/psc_Darwin_x86_64.tar.gz"
      sha256 "f898d969516d50bb5baf1ba995699decb21d4bede64707fe48a8f6c72db4b3fd"

      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.0/psc_Darwin_arm64.tar.gz"
      sha256 "ff6bc17e0c7cb73405825036e305f7f1cf41ca545437dd6ff15c00edc574a3b3"

      def install
        bin.install "psc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.0/psc_Linux_x86_64.tar.gz"
      sha256 "14f88e266f443d905a35b93558d2099ed40d59e9d8d53986a8e5a61179bf91de"
      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.1.0/psc_Linux_arm64.tar.gz"
      sha256 "23021a0d6f610269a158af22ed60886dc8a7c36110c3e133eb2d1a7a22b45816"
      def install
        bin.install "psc"
      end
    end
  end

  test do
    system "#{bin}/psc --version"
  end
end
