# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psc < Formula
  desc "postgres copy utility"
  homepage ""
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.0.0/psc_Darwin_x86_64.tar.gz"
      sha256 "4e5aeee694cfc7d63401b1d4dd8e3c903d432abbf3fe7b75c46a5fe30ddb85c6"

      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.0.0/psc_Darwin_arm64.tar.gz"
      sha256 "ee029eaa81222dc9889444ba4f2cc05b73b8ed3e8b488a418d84fa6e70b9435c"

      def install
        bin.install "psc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.0.0/psc_Linux_x86_64.tar.gz"
      sha256 "5802aa10191043af4364c0a07de4b2a9374406328d7db69a3a13522d35bdd2b1"
      def install
        bin.install "psc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psc/releases/download/v2.0.0/psc_Linux_arm64.tar.gz"
      sha256 "7986d67bc33cb187f590ac156e0a335ac3fa47998f756b258345f4ffd09541bf"
      def install
        bin.install "psc"
      end
    end
  end

  test do
    system "#{bin}/psc --version"
  end
end
