# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psq < Formula
  desc "lightweight postgres monitor for the terminal"
  homepage ""
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.6.0/psq_Darwin_x86_64.tar.gz"
      sha256 "5095c9678fb8b5676546dd260d08253673d807517ddca25eebec3c4196ed2ff0"

      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.6.0/psq_Darwin_arm64.tar.gz"
      sha256 "b18ef060301a242382de1b0da14090f623781e41ed412602be4188dede592a21"

      def install
        bin.install "psq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.6.0/psq_Linux_x86_64.tar.gz"
      sha256 "9ba715b9e3754f942c1c33d09f85310d4c979fb445622b12dd59ff0fbf5da8b6"
      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.6.0/psq_Linux_arm64.tar.gz"
      sha256 "01fa695dbdd194aa0950daa7f8a358403cef72cd4d927496e46eee76c35e326c"
      def install
        bin.install "psq"
      end
    end
  end

  test do
    system "#{bin}/psq --version"
  end
end
